# Generated by Django 2.2.19 on 2024-12-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='janr',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
